---
- hosts: Host
  tasks:
  - apt_repository:
      repo: "{{ item }}"
    with_items:
      - "deb http://10.20.13.120/repo/smolensk/repository-update-9 smolensk contrib main non-free"
      - "deb http://10.20.13.120/repo/smolensk/repository-update-xrdp smolensk contrib main non-free"
      - "deb http://10.20.13.120/repo/smolensk/mounted-iso-main smolensk contrib main non-free"
      - "deb http://10.20.13.120/repo/smolensk/smolensk_iso smolensk main non-free contrib"
      - "deb http://10.20.13.120/repo/smolensk/repository-update-9-dev smolensk contrib main non-free"
  - apt:
      name: apache2
      state: present
  - name: Смена AstraMode
    lineinfile: 
      path: /etc/apache2/apache2.conf
      search_string: "# AstraMode on"
      line: "AstraMode off"
  - name: Скорее всего надо будет функцию копирования выставить (Пока не проверю не пойму)
    template: 
      src: /etc/apache2/sites-enabled/Reposit.conf
      dest: /etc/apache2/sites-enabled
      owner: Hel2lowJack
      group: Host
      mode: '0644'
  - shell: sudo a2ensite Reposit.conf
  - shell: sudo a2dissite 000-default.conf
  - name: Перезагрузка сервера
    shell: sudo systemctl restart apache2