---
- hosts: Group_B
  tasks:
  - name: Create file
    copy:
      src: /home/littleone/work/Hello_work.py
      dest: /home/jack
    delegate_to: 192.168.1.3
  - name: File
    copy:
      src: /home/littleone/work/Hello_work.py
      dest: /home/jacktime
    delegate_to: 192.168.1.2