---
- name: Playbook to copy files
  hosts: all
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /home/littleone/work/Hello_work.py
      dest: /home/Hello_work.py

  - name: Deligate to L3
    copy:
      src: /home/littleone/work/Hello_work.py
      dest: /home/Hello_work.py
    deligate_to: L3