---
- hosts: all
  tasks:
  - name: Create file
    copy:
      src: /home/littleone/work/Prot.py
      dest: /home/{{ansible_user}}
  - name: Starting to work with the program  
    script: Prot.py -n {{name}} -l {{str}} {{command}} {{num}}
    register: command_output
    args:
      executable: python3
  - name: Command output exit with...
    ansible.builtin.debug:
      var: command_output.stdout_lines