---
- hosts: Hosts
  tasks:
  - name: Create file
    copy:
      src: /home/littleone/work/Hello_work.py
      dest: /home/{{ansible_user}}
  - name: Do hast   
    script: Hello_work.py multi {{name}} {{num}}
    register: command_output
    args:
      executable: python3
  - name: command output
    ansible.builtin.debug:
      var: command_output.stdout_lines